const PAGINATION = {
  DEFAULT_PAGINATION: "16",
  DEFAULT_TABLE_PAGE_SIZE: 8,
  ARROW_COLOR: "#454545",
  DISABLED_ARROW_COLOR: "#9e9e9e",
  DEFAULT_TABLE_PAGE_INDEX: 1,
  DEFAULT_REVIEW_TABLE_PAGE_SIZE: 4,
};

export { PAGINATION };
