export const REQUIRED_PORTAL_KEYS = ["PortalId", "LocaleId", "PublishState", "PublishCatalogId", "PortalLocales", "StoreCode", "ThemeName", "CatalogCode"];
export const AVAILABLE_THEME_NAME = ["B2B", "theme1", "theme2", "B2B_B2B"];
export const REQUIRED_DOMAIN_KEYS = ["StoreCode", "ApplicationType"];
export const DEFAULT_THEME_COLORS = `:root {
    --primary: #000000;
    --secondary: #ffffff;
    --primary-btn-bg: #000000;
    --secondary-btn-bg: #ffffff;
    --primary-btn-text: #ffffff;
    --secondary-btn-text: #000000;
    --btn-border: #000000;
    --btn-border-radius: 0.25rem;
    --header-bg: #ffffff;
    --footer-bg: #000000;
    --footer-primary-text: #FFFFFF;
    --footer-secondary-text: #FFFFFF;
    --navigation-bar-bg: #f3f4f6;
    --navigation-text: #605458;
    --link: #1e40af;
    --hover: #3b82f6;
    --success: #22c55e;
    --error: #ef4444;
    --border-color: #9ca3af;
    --breadcrumbs-text: #9a9a9a;
    --card-radius: 0.25rem;
    --card-border: #e2e8f0;
    --input-radius: 0.25rem;
    --input-border: #d3d3d3;
    --separator: #9ca3af;
    --accent: #000000;
    --widget-edit-bar: #5db043;
  }`;